# Generated by Django 3.0.5 on 2020-11-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationm',
            options={'managed': False},
        ),
    ]
