# Generated by Django 3.0.5 on 2020-11-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_finder', '0002_auto_20201129_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationm',
            options={},
        ),
    ]
